[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -ra -v
log_cli = false
filterwarnings =
	ignore::DeprecationWarning
markers = 
    verified: mark test as verified with a known good output (e.g., from a previous run or manual verification)